ALTER TABLE jobs DROP CONSTRAINT IF EXISTS jobs_job_type_check;

ALTER TABLE jobs
    ADD CONSTRAINT jobs_job_type_check
    CHECK (job_type IN ('INGEST_RANGE', 'BACKFILL_RANGE', 'REPLAY_RANGE', 'VERIFY_REORG', 'REPAIR_CHECKPOINT'));
